name: Build Kernel A51 Pro

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev libelf-dev clang lld llvm

      - name: Compile Kernel
        run: |
          # On utilise le Clang déjà présent sur le système GitHub
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CC=clang
          export CLANG_TRIPLE=aarch64-linux-gnu-
          
          # Nettoyage automatique des erreurs Samsung
          find drivers/media/platform/exynos/ -type f \( -name "*.h" -o -name "*.c" \) -exec sed -i 's/#define warn_common.*/#define warn_common(fmt, ...) do {} while(0)/g' {} +
          find drivers/media/platform/exynos/ -type f \( -name "*.h" -o -name "*.c" \) -exec sed -i 's/#define fimc_is_warn.*/#define fimc_is_warn(fmt, ...) do {} while(0)/g' {} +

          # Configuration
          make vendor/a51_defconfig
          
          # On force la compilation avec le Clang du système
          make -j$(nproc) CC=clang CLANG_TRIPLE=aarch64-linux-gnu-

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-A51
          path: arch/arm64/boot/Image.gz-dtb
