name: Build Kernel A51

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Toolchain
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev libelf-dev gcc-aarch64-linux-gnu

      - name: Compile Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # --- CORRECTIF SYNTAXE ---
          # On utilise une boucle pour modifier les fichiers sans faire d'erreur 'find'
          for f in $(find drivers/media/platform/exynos/ -name "*.h"); do
            sed -i 's/#define warn_common.*/#define warn_common(fmt, ...) do {} while(0)/g' "$f"
            sed -i 's/#define fimc_is_warn.*/#define fimc_is_warn(fmt, ...) do {} while(0)/g' "$f"
          done

          for f in $(find drivers/media/platform/exynos/ -name "*.c"); do
            sed -i 's/warn("the size of STATB buffer is too small/\/\/warn("the size of STATB buffer is too small/g' "$f"
          done
          # --------------------------

          make vendor/a51_defconfig
          
          # On force l'ignorance des erreurs au maximum
          export KCFLAGS="-w -Wno-error -Wno-implicit-function-declaration"
          
          make -j$(nproc) KCFLAGS="$KCFLAGS"

      - name: Upload Boot Image
        uses: actions/upload-artifact@v4
        with:
          name: boot-image
          path: arch/arm64/boot/Image.gz-dtb
          